FROM tensorflow/tensorflow:0.10.0rc0

RUN apt-get update && apt-get install -y \
        dbus \
        supervisor \
        cmake \
        libboost-all-dev \
        python-tk \
        libsdl2-dev \
        xvfb

WORKDIR /home

# D-Bus library setup of the machine's uuid
RUN dbus-uuidgen > /etc/machine-id

RUN mkdir -p /var/log/xvfb
RUN mkdir -p /var/log/supervisord

# Point DISPLAY enviroment variable to Xvfb's display :1 and screen 0 
ENV DISPLAY :1.0

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf